name: Generate website

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 19
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Install npm dependencies
        run: |
          npm i -g svgo && npm ci
        env:
          CI: true
      - name: Install latest imagemagick
        run: |
          sudo apt update && \
          sudo apt install libfontconfig1 fontconfig libfontconfig1-dev libharfbuzz-dev libfribidi0 && \
          mkdir /tmp/magick && \
          cd /tmp/magick && \
          curl -sL https://imagemagick.org/archive/binaries/magick -o magick.AppImage && \
          chmod +x magick.AppImage && \
          ./magick.AppImage --appimage-extract && \
          echo "LD_LIBRARY_PATH=$(realpath ./squashfs-root/usr/lib)" >> $GITHUB_ENV && \
          echo "PATH=$PATH:$(realpath ./squashfs-root/usr/bin)" >> $GITHUB_ENV
      - name: Generate website
        run: node index.js
      - name: Upload artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: site
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: site
      - name: 🚀 (GitHub pages)
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: site
          SINGLE_COMMIT: true
