name: Generate website

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 20
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Install npm dependencies
        run: |
          npm i -g svgo && npm ci
        env:
          CI: true
      - name: Install rsvg-convert
        run: |
          sudo apt update && \
          sudo apt install librsvg2-bin
      - name: Generate website
        if: github.ref == 'refs/heads/master'
        run: npm run build
      - name: Generate website (draft)
        if: github.ref == 'refs/heads/draft'
        run: npm run build-draft
      - name: Upload artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: site
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: site
      - name: 🚀 (GitHub pages)
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: site
          SINGLE_COMMIT: true

  deploy_draft:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/draft'
    steps:
      - uses: actions/checkout@v1
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: site
      - name: 🚀 (drafts branch)
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: draft-dist
          FOLDER: site
          SINGLE_COMMIT: true
