name: Generate website

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install npm dependencies
        run: |
          npm i -g svgo && npm ci
        env:
          CI: true
      - name: Generate website
        run: node index.js
      - name: Upload artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: site
          path: ./dist
      - name: 🚀 (GitHub pages)
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          SINGLE_COMMIT: true
